#!/bin/sh

case $1 in
	configure)

		#le groupe leterrier a ete cree par le paquet abuledu-leterrier-common
		chgrp -R leterrier /usr/share/abuledu-mulot/{images,reglages}
		chmod -R g+w /usr/share/abuledu-mulot/{images,reglages}

		# si l'utilisateur abuladmin existe on lui donne le répertoire
		# des images pour qu'il puisse y faire le gendarme
		TESTU=`getent passwd | grep ^abuladmin:` || true
		if [ -n "${TESTU}" ]; then
		  chown -R abuladmin /usr/share/abuledu-mulot/{images,reglages}
		fi

		if [ -x /usr/bin/update-menus ]; then
		  update-menus
		fi

		;;
	*)
		true
		;;
esac

